// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "KarasPatcher.h"
const char *newprojectfilename;
const char *openprojectfilename;
char filename[MAX_PATH];

fltk::Window *Window=(fltk::Window *)0;

fltk::Item *MenuNewProject=(fltk::Item *)0;

static void cb_MenuNewProject(fltk::Item*, void*) {
  newprojectfilename = fltk::file_chooser ("New Project", "CiMPatcher Project Files (*.{CiMP})\t",&filename[0] , 0);
  if(newprojectfilename != 0) strcpy((char *)&filename[0],newprojectfilename);
}

fltk::Item *MenuOpenProject=(fltk::Item *)0;

static void cb_MenuOpenProject(fltk::Item*, void*) {
  openprojectfilename = fltk::file_chooser ("Open Project", "CiMPatcher Project Files (*.{CiMP})\t",&filename[0] , 0);
  if(openprojectfilename != 0) strcpy((char *)&filename[0],openprojectfilename);
}

fltk::Item *MenuExit=(fltk::Item *)0;

static void cb_MenuExit(fltk::Item*, void*) {
  Window->destroy();
}

fltk::Item *about=(fltk::Item *)0;

static void cb_about(fltk::Item*, void*) {
  about_window()->exec (Window,0);
}

fltk::Group *infotab=(fltk::Group *)0;

fltk::Input *teamin=(fltk::Input *)0;

fltk::Input *teamwebsitein=(fltk::Input *)0;

fltk::LightButton *teamornoteam=(fltk::LightButton *)0;

static void cb_teamornoteam(fltk::LightButton*, void*) {
  static bool team = true;
    if (team)
    {
    teamin->deactivate();
    }
    else
    {
    teamin->activate();
    }
    team = !team;
  Window->redraw();
}

fltk::LightButton *webnoweb=(fltk::LightButton *)0;

static void cb_webnoweb(fltk::LightButton*, void*) {
  static bool web = true;
    if (web)
    {
    teamwebsitein->deactivate();
    }
    else
    {
    teamwebsitein->activate();
    }
    web = !web;
  Window->redraw();
}

fltk::Button *nextbutton=(fltk::Button *)0;

fltk::Button *previousbutton=(fltk::Button *)0;

fltk::Button *boutonexit=(fltk::Button *)0;

static void cb_boutonexit(fltk::Button*, void*) {
  Window->destroy();
}

fltk::Window* main_window() {
  fltk::Window* w;
   {fltk::Window* o = Window = new fltk::Window(505, 356, "The Karas Patcher 0.0 (Beta 0)");
    w = o;
    o->begin();
     {fltk::MenuBar* o = new fltk::MenuBar(0, 0, 505, 23);
      o->align(fltk::ALIGN_CENTER);
      o->begin();
       {fltk::ItemGroup* o = new fltk::ItemGroup("&File");
        o->begin();
         {fltk::Item* o = MenuNewProject = new fltk::Item("New Project ...");
          o->shortcut(0x4006e);
          o->callback((fltk::Callback*)cb_MenuNewProject);
        }
         {fltk::Item* o = MenuOpenProject = new fltk::Item("Open Project ...");
          o->shortcut(0x4006f);
          o->callback((fltk::Callback*)cb_MenuOpenProject);
        }
         {fltk::Divider* o = new fltk::Divider();
          o->box(fltk::BORDER_BOX);
        }
         {fltk::Item* o = MenuExit = new fltk::Item("Exit");
          o->shortcut(0x80078);
          o->callback((fltk::Callback*)cb_MenuExit);
        }
        o->end();
      }
       {fltk::ItemGroup* o = new fltk::ItemGroup("&About");
        o->begin();
         {fltk::Item* o = about = new fltk::Item("What about us ...");
          o->shortcut(0x4ffbe);
          o->callback((fltk::Callback*)cb_about);
        }
        o->end();
      }
      o->end();
    }
     {fltk::Group* o = infotab = new fltk::Group(0, 30, 505, 285);
      o->box(fltk::BORDER_BOX);
      o->align(fltk::ALIGN_CENTER);
      o->begin();
       {fltk::Input* o = new fltk::Input(27, 24, 450, 20, "Cracker ");
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::BORDER_BOX);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      }
       {fltk::Input* o = teamin = new fltk::Input(27, 57, 450, 20, "Team ");
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::BORDER_BOX);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      }
       {fltk::Input* o = teamwebsitein = new fltk::Input(27, 91, 450, 20, "Cracker's or team's website ");
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::BORDER_BOX);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
        o->text("http://");
      }
       {fltk::Input* o = new fltk::Input(27, 127, 450, 20, "Prog Name ");
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::BORDER_BOX);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      }
       {fltk::TextEditor* o = new fltk::TextEditor(27, 163, 450, 107, "About");
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::BORDER_BOX);
        o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      }
       {fltk::LightButton* o = teamornoteam = new fltk::LightButton(8, 45, 15, 15);
        o->set_vertical();
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::FLAT_BOX);
        o->selection_color((fltk::Color)0x50505000);
        o->callback((fltk::Callback*)cb_teamornoteam);
      }
       {fltk::LightButton* o = webnoweb = new fltk::LightButton(8, 78, 15, 15);
        o->set_vertical();
        o->box(fltk::BORDER_BOX);
        o->buttonbox(fltk::FLAT_BOX);
        o->selection_color((fltk::Color)0x50505000);
        o->callback((fltk::Callback*)cb_webnoweb);
      }
      o->end();
    }
     {fltk::Button* o = nextbutton = new fltk::Button(420, 325, 85, 29, "&Next              @->");
      o->box(fltk::BORDER_BOX);
      o->buttonbox(fltk::BORDER_BOX);
      o->highlight_color((fltk::Color)0xa0a0a000);
      o->highlight_textcolor((fltk::Color)0x50505000);
      o->shortcut(0x4006e);
    }
     {fltk::Button* o = previousbutton = new fltk::Button(332, 325, 85, 29, "@<-      \302\240&Previous");
      o->box(fltk::BORDER_BOX);
      o->buttonbox(fltk::BORDER_BOX);
      o->highlight_color((fltk::Color)0xa0a0a000);
      o->highlight_textcolor((fltk::Color)0x50505000);
      o->shortcut(0x40070);
    }
     {fltk::Button* o = boutonexit = new fltk::Button(0, 324, 85, 30, "E&xit");
      o->box(fltk::BORDER_BOX);
      o->buttonbox(fltk::BORDER_BOX);
      o->highlight_color((fltk::Color)0xa0a0a000);
      o->highlight_textcolor((fltk::Color)0x50505000);
      o->shortcut(0x40078);
      o->callback((fltk::Callback*)cb_boutonexit);
    }
    o->end();
    
    
    fltk::open_display();
    o->icon((const void *)LoadIcon(fltk::xdisplay, MAKEINTRESOURCE(IDI_ICON2)));
    o->Rectangle::set(fltk::Monitor::find(0,0),o->w(),o->h(),fltk::ALIGN_CENTER);
  }
  return  w;
}

fltk::DoubleBufferWindow *aboutuswindow=(fltk::DoubleBufferWindow *)0;

fltk::ReturnButton *aboutusokbutton=(fltk::ReturnButton *)0;

static void cb_aboutusokbutton(fltk::ReturnButton*, void*) {
  aboutuswindow->destroy();
  Window->redraw();
}

fltk::DoubleBufferWindow* about_window() {
  fltk::DoubleBufferWindow* w;
   {fltk::DoubleBufferWindow* o = aboutuswindow = new fltk::DoubleBufferWindow(308, 206, "What about us");
    w = o;
    o->type(241);
    o->box(fltk::BORDER_BOX);
    o->buttonbox(fltk::BORDER_BOX);
    o->begin();
     {fltk::ReturnButton* o = aboutusokbutton = new fltk::ReturnButton(245, 180, 60, 25, "Ok");
      o->box(fltk::BORDER_BOX);
      o->buttonbox(fltk::BORDER_BOX);
      o->highlight_color((fltk::Color)0xa0a0a000);
      o->highlight_textcolor((fltk::Color)0x50505000);
      o->shortcut(0xff0d);
      o->callback((fltk::Callback*)cb_aboutusokbutton);
    }
    o->end();
    o->Rectangle::set(fltk::Monitor::find(0,0),o->w(),o->h(),fltk::ALIGN_CENTER);
    o->set_non_modal();
    o->clear_border();
    o->resizable(o);
  }
  return  w;
}

#include <fltk/run.h>

int main (int argc, char **argv) {

  fltk::Window* w;
  w = main_window();
  w->show(argc, argv);
  return  fltk::run();
}
